### PR TITLE
Add Paw as sponsor. Add all sponsor links.

### PR DESCRIPTION
**Pull request by mittsh**
- [x] Add links to all sponsors
- [x] Add Paw as sponsor

image
- [x] Update internet speed

image
- [x] Update sponsor links to flexbox & make it responsive

image

image

### CODE REVIEW

**Comment by revolunet** [comment]
yessss thanks !

**Comment by mittsh** [comment]
😄

**Comment by revolunet** [comment]
manque le logo paw :)

**Comment by mittsh** [comment]
ouais… je fais un PR

**Pull request merged**
